baseURL: https://kube-runner.docs.drone.io
languageCode: en-us
title: Drone Kubernetes Runner
theme: drone-hugo-theme

pygmentsUseClasses: true
pygmentsCodefences: true

outputs:
  home: ["HTML", "JSON"]
